### ISSUE TITLE
Hot reloading is not working

### ISSUE THREAD

**Issue by NicholasPeretti** [jxnblk/mdx-deck#476] opened 2019-09-11 05:47 UTC
# Environment
**Machine**: MacBook Pro 15" 2018 
**Browser**: Chrome (version 76.0.3809.132)

# Description
I was trying this awesome package in order to create some slides for my tech talk.
I've followed the instructions on the readme of this repo, so my files are:
- package.json
- deck.mdx
- yarn.lock
- node_modules
which is pretty standard. The start script is `mdx-deck deck.mdx`.

# What should happen?
When I run `yarn start`, I expect the program to start, build the app and serve it in the `8000` port of my browser. Furthermore, I want to see hot-reloaded changes every time I edit my `deck.mdx`

# What happen instead?
The program creates the first build form the files and serves it correctly on the port `8000` of my browser.
Anyhow, when I change a file I can see from the console that Webpack recompile the code but no changes appear on my browser page.
At this point I launch a refresh of the page, expecting the changes to be shown on the page. One again I'm not able to see them.

In order to actually navigate an updated version of my app I need to stop the program and re-run `yarn start`, which is painful.

**Comment by NicholasPeretti** [comment] 2019-09-11 06:26
After some tests I've noticed that, if I have more slides, I need to edit the first one to trigger the hot reloading. Otherwise I won't see the edit, just like described in #474 .

Anyway, at the beginning I had only one slide and the hot reloading wasn't working in there.

I've tried to create a sandbox and tried to reproduce the error but everything seems to work in there. I'll create a repo on GitHub in order to allow you to reproduce the error on your machines.

**Comment by NicholasPeretti** [comment] 2019-09-11 06:30
# I think I know what's happening here
I was working **without** a git repo in the project folder. As soon as I created it everything started working normally. 

I guess hot reloading uses git APIs in order to detect changes, I don't have any clue on this.
Anyhow, this issue could be related to #474

**Comment by jonsherrard** [comment] 2019-09-11 17:33
@NicholasPeretti just out of interest, are using VSCode?

**Comment by NicholasPeretti** [comment] 2019-09-11 17:42
@jonsherrard  Yes, do you think it's related to the issue?

**Comment by jonsherrard** [comment] 2019-09-12 00:41
@NicholasPeretti - I don't think it's a git issue as my repro on #474 is on Github! Not VSCode issue either as I just moved to an entirely different machine that only has Vim on it, and I'm getting the same issue there.

**Comment by NicholasPeretti** [comment] 2019-09-13 07:59
@jonsherrard Thank you for finding the time to look into it. I've tried your solution and now I have the exact same problem of #474, it hot-reloads only when the first slide changes.

**Comment by jonsherrard** [comment] 2019-09-13 08:23
Could you not get it to work by pinning the Gatsby version?

**Comment by NicholasPeretti** [comment] 2019-09-13 10:04
Nope. 

I've tried to delete both the `node_modules` directory and the `yarn.lock` file (I use yarn).
Then I've typed:
`yarn add gatsby@2.14.7 --exact`
`yarn add mdx-deck`

After that I've tried to start the project with `yarn start` and I have the same problem described in #474

**Comment by jonsherrard** [comment] 2019-09-13 17:00
And if you go into node_modules/gatsby and open package.json the version is 2.14.7?

**Comment by NicholasPeretti** [comment] 2019-09-16 05:38
@jonsherrard  Yes, it is

**Comment by ravanscafi** [comment] 2019-09-19 18:07
I'm having the same issue, I'm unable to make it work :cry:

**Comment by jxnblk** [comment] 2019-09-23 20:32
Duplicate of #474

**Closed by jxnblk** 2019-09-23 20:32 UTC
