### ISSUE TITLE
Fails to start on Windows 10 (build 1903)

### ISSUE THREAD

**Issue by dance2die** [jxnblk/mdx-deck#416] opened 2019-07-24 04:40 UTC
## 🐛 Issue

MDX-deck fails to run with `mdx-deck deck.mdx` on Windows 10.

## 🐾 Reproduce Steps

(Failing code available here - https://github.com/dance2die/demo.mdx-error-on-windows10)

1. `npm init -y`
1. `npm i -D mdx-deck`
1. Create `deck.mdx` with following content

```markdown
# This is the title of my deck

---

# About Me

---


# The end

```

4. Start the server with `mdx-deck deck.mdx`

Following error message shows up

```bash
C:\misc\src\throwaway\temp\mdxdeck  (mdxdeck@1.0.0) 
λ npm start

> mdxdeck@1.0.0 start C:\misc\src\throwaway\temp\mdxdeck
> mdx-deck deck.mdx

info Deleting .cache, public
info Successfully deleted directories

success open and validate gatsby-configs - 0.109 s
success load plugins - 0.493 s
success onPreInit - 0.063 s
success initialize cache - 0.071 s
success copy gatsby files - 0.219 s
success onPreBootstrap - 0.073 s
success source and transform nodes - 0.720 s
success building schema - 0.202 s
success createPages - 0.134 s
success createPagesStatefully - 0.090 s
success onPreExtractQueries - 0.063 s
success update schema - 0.080 s
success extract queries from components - 0.261 s
success write out requires - 0.093 s
success write out redirect data - 0.066 s
success onPostBootstrap - 0.067 s
⠀
info bootstrap finished - 5.884 s
⠀
success run static queries - 0.067 s
success run page queries - 0.127 s — 2/2 36.46 queries/second


C:\misc\src\throwaway\temp\mdxdeck  (mdxdeck@1.0.0)
λ npm start

> mdxdeck@1.0.0 start C:\misc\src\throwaway\temp\mdxdeck> mdx-deck deck.mdx

info Deleting .cache, public
info Successfully deleted directories

success open and validate gatsby-configs - 0.107 s
success load plugins - 0.491 s
success onPreInit - 0.057 s
success initialize cache - 0.063 s
success copy gatsby files - 0.186 s
success onPreBootstrap - 0.070 s
success source and transform nodes - 0.600 s
success building schema - 0.235 s
success createPages - 0.121 s
success createPagesStatefully - 0.085 s
success onPreExtractQueries - 0.055 s
success update schema - 0.075 s
success extract queries from components - 0.226 s
success write out requires - 0.098 s
success write out redirect data - 0.060 s
success onPostBootstrap - 0.061 s
⠀
info bootstrap finished - 5.505 s
⠀
success run static queries - 0.058 s
success run page queries - 0.101 s — 2/2 45.84 queries/second

 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (10:4)

File: ..\@mdx-deck\themes\dots.js:10:4


 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (11:9)

File: ..\@mdx-deck\themes\syntax-highlighter-prism.js:11:9


 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (17:9)

File: ..\@mdx-deck\themes\syntax-highlighter.js:17:9


Error: Command failed with exit code 1 (Unknown system error -1): gatsby develop --host localhost --port 8000 --open
    at makeError (C:\misc\src\throwaway\temp\mdxdeck\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\misc\src\throwaway\temp\mdxdeck\node_modules\execa\index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdxdeck@1.0.0 start: `mdx-deck deck.mdx`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdxdeck@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dance2die\AppData\Roaming\npm-cache\_logs\2019-07-24T04_27_46_626Z-debug.log

C:\misc\src\throwaway\temp\mdxdeck  (mdxdeck@1.0.0) 
λ 
```

## 🖼 Screenshot

![image](https://user-images.githubusercontent.com/8465237/61765436-0ff15d80-adab-11e9-9b30-d8d898881a3b.png)

## ➕ Additional Info

1. The same steps work on Ubuntu 19.04 w/ node version 12.x
2. Error occurs on Windows 10 with node version 10.x, 11.x, and 12.x

**Comment by malcolm-kee** [comment] 2019-07-25 11:38
I believe this is due to `gatsby-plugin-compile-es6-packages` does not work for scoped packages in Windows.
I've investigated and raised [an issue](https://github.com/robwalkerco/gatsby-plugin-compile-es6-packages/issues/4) for that package, hopefully once that issue is resolve this is fixed as well!

**Comment by dance2die** [comment] 2019-07-25 15:20
Thank you @malcolm-kee for looking into the issue and coming up with the patch 🙂

**Comment by SeanKilleen** [comment] 2019-07-25 17:44
Thanks to @malcolm-kee a fix has been merged & pushed for this dependency. `v2.1.0` of the package should resolve the issue.

**Comment by SeanKilleen** [comment] 2019-07-25 17:53
Confirmed: updating that package within my dependency tree to v2.1.0 resolves the issue. Have I mentioned OSS is amazing? :)

**Comment by dance2die** [comment] 2019-07-25 17:58
Thank you @malcolm-kee & @SeanKilleen~

Works well now~ 😀

And yes, @SeanKilleen OSS is awesome~

![thank you](https://user-images.githubusercontent.com/8465237/61897036-323ac680-aee4-11e9-93d3-b8d834afe1eb.gif)

**Closed** 2019-07-25 17:58 UTC
