### ISSUE TITLE
TypeError: Cannot read property 'internal' of null

### ISSUE THREAD

**Issue by alhansrisuk** [jxnblk/mdx-deck#623] opened 2020-01-09 17:03 UTC
Created a deck template with `mdx-deck` and am running into issues with theming, layouts, and hot-reloading. If I make a change in my `.mdx` file and save it, it will give me this error:
![image](https://user-images.githubusercontent.com/194897/72088163-9f49e900-32d7-11ea-9465-7fd4bf7e2c7a.png)

The only thing I have as a devDependency is `mdx-deck`. 

Also, i'm having issues with theming to work as well. I have this line at the top of my `.mdx` file to use the future theme:
`export { future as theme } from 'mdx-deck/themes'`
but then I run `npm start` and it looks like I get console errors here:
![image](https://user-images.githubusercontent.com/194897/72088379-0a93bb00-32d8-11ea-83d3-59ca59f929fd.png)

**Comment by alhansrisuk** [comment] 2020-01-10 12:50
Also with Layouts, after `npm start` I get this error in the browser:
![image](https://user-images.githubusercontent.com/194897/72154140-d5da3f00-337d-11ea-9fa5-72a57e305ae4.png)

**Comment by jxnblk** [comment] 2020-01-10 16:07
Duplicate of #598

**Closed by jxnblk** 2020-01-10 16:07 UTC
