### ISSUE TITLE
PDF export of slides with code-surfer doesn't seem to be supported

### ISSUE THREAD

**Issue by ledicjp** [jxnblk/mdx-deck#211] opened 2018-10-30 14:57 UTC
Is it only me or is the export to PDF not supported for slides that use the code-surfer library?

**Comment by jxnblk** [comment] 2018-11-12 08:48
Possible duplicate of #183

**Comment by jxnblk** [comment] 2019-04-20 23:16
With the changes in v2, Code Surfer will need to have a default view of showing whatever makes sense when `steps === Infinity` - closing this here, but feel free to continue the discussion on the Code Surfer repo

**Closed by jxnblk** 2019-04-20 23:16 UTC
