### ISSUE TITLE
Can't use `Image` inside `Split`

### ISSUE THREAD

**Issue by pvinis** [jxnblk/mdx-deck#429] opened 2019-08-05 16:57 UTC
It just doesn't render.

**Comment by jxnblk** [comment] 2019-08-05 21:14
The `Image` component is for rendering a background image for the entire slide. I'm guessing it's rendering with messed up styles inside of `Split` If you want an image side-by-side with other content, either use `![alt](image.png)` or the `<img />` tag in `Split`

**Comment by pvinis** [comment] 2019-08-06 07:26
I did try with `![](images/my.png)` but it rendered a blue question mark, so I wasn't sure what the problem is there..

**Comment by HoverBaum** [comment] 2019-08-07 08:29
This could well be related to #401, about static assets (such as images) not being picked up and hosted.

**Comment by jxnblk** [comment] 2019-09-23 20:35
Duplicate of #401

**Closed by jxnblk** 2019-09-23 20:35 UTC
