### ISSUE TITLE
Presenter view's "next" slide should account for Appear animations

### ISSUE THREAD

**Issue by vlsi** [jxnblk/mdx-deck#282] opened 2019-03-20 07:52 UTC
mdx-deck 1.10.2

```jsx
import { Appear, components } from 'mdx-deck'
const Ul = components.ul
const Li = components.li

## Slide 1

<Ul>
<Li>One</Li>
<Appear>
<Li>Two</Li>
<Li>Three</Li>
</Appear>
</Ul>

---

## Slide 2

<Ul>
<Li>Four</Li>
<Appear>
<Li>Five</Li>
<Li>Six</Li>
</Appear>
</Ul>
```

## Issue

Presenter view shows "current slide" (e.g. "Slide 1"), and the next slide shows Slide 2 no matter what is the animation sequence at the moment.

## Expected behavior

Presenter view's "next" should show the state which the screen will have after pressing "right arrow".

In other words, presenter view should show `#1.2`, `#1.3` substates as well

**Comment by jxnblk** [comment] 2019-03-23 18:59
Duplicate of #76

**Closed by jxnblk** 2019-03-23 18:59 UTC
