### ISSUE TITLE
Working with custom theme and backgroundImage

### ISSUE THREAD

**Issue by Kampfheizung** [jxnblk/mdx-deck#458] opened 2019-08-30 15:19 UTC
Hey we're having a problem with upgrading from `2.5.1` to `3.*` because the background Image isn't set anymore. We already checked if the url from the `backgroundImage` is wrong but the `backgroundImage` style is not even set inside our style tags. Can you help us out with this problem?

Our custom theme looks like that:
```js
import { syntaxHighlighterPrism } from "@mdx-deck/themes";
import okaidia from "react-syntax-highlighter/dist/esm/styles/prism/okaidia";

export default syntaxHighlighterPrism({
  font: "system-ui, sans-serif",
  monospace: "Menlo, monospace",
  pre: {
    textAlign: "left"
  },
  ol: {
    textAlign: "left"
  },
  ul: {
    textAlign: "left"
  },
  styles: {
    backgroundImage: "url(../images/background.svg)",
    backgroundPosition: "top right",
    backgroundRepeat: "no-repeat",
    fontSize: "16px",
    textAlign: "center",
    "@media screen and (min-width:56em)": {
      fontSize: "32px"
    },
    "@media screen and (min-width:64em)": {
      fontSize: "48px"
    },
    "@media print": {
      fontSize: "40px"
    },
    "li > p": {
      margin: 0
    }
  },

  colors: {
    text: "rgb(61, 77, 101)",
    background: "white",
    link: "#07c",
    pre: "#f0f",
    preBackground: "#333",
    code: "#f0f"
  },

  prism: {
    style: okaidia
  }
});

```

The style tags:
```html
<style data-emotion="css-global">
      body {
        margin: 0;
      }
    </style>
    <style data-emotion="css">
      .css-bdfrlc {
        width: 100vw;
        height: 100vh;
      }
    </style>
    <style data-emotion="css">
      .css-bdfrlc * {
        box-sizing: border-box;
      }
    </style>
    <style data-emotion="css">
      .css-oh60dh-Slide {
        box-sizing: border-box;
        width: 100%;
        height: 100%;
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-flex-direction: column;
        -ms-flex-direction: column;
        flex-direction: column;
        -webkit-align-items: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: center;
        -webkit-justify-content: center;
        -ms-flex-pack: center;
        justify-content: center;
        overflow: hidden;
        position: relative;
        color: rgb(61, 77, 101);
        background-color: white;
        font-family: system-ui, sans-serif;
        font-size: 20px;
      }
    </style>
    <style data-emotion="css">
      @media screen and (min-width: 40em) {
        .css-oh60dh-Slide {
          font-size: 24px;
        }
      }
    </style>
    <style data-emotion="css">
      @media screen and (min-width: 52em) {
        .css-oh60dh-Slide {
          font-size: 32px;
        }
      }
    </style>
    <style data-emotion="css">
      @media screen and (min-width: 64em) {
        .css-oh60dh-Slide {
          font-size: 48px;
        }
      }
    </style>
    <style data-emotion="css">
      .css-1djqpdg {
        font-family: inherit;
        line-height: 1.125;
        font-weight: 700;
      }
    </style>
    <style data-emotion="css">
      .css-zbzbt1 {
        color: #07c;
      }
    </style>
    <style data-emotion="css">
      .css-1kh5aro {
        width: 100vw;
        height: 1306px;
      }
    </style>
    <style data-emotion="css">
      .css-1kh5aro * {
        box-sizing: border-box;
      }
    </style>
```

**Comment by jxnblk** [comment] 2019-08-30 16:43
Sounds like a possible duplicate of #401

**Comment by jxnblk** [comment] 2019-09-23 20:35
Duplicate of #401

**Closed by jxnblk** 2019-09-23 20:35 UTC
